### ISSUE TITLE
Support Object.assign

### ISSUE THREAD

**Issue by austin-rausch** [raptorjs/raptor-polyfill#2]
Support for the `Object.assign` method would be useful. [Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) is a link to the MDN page.  According to the compatibility table its a relatively new feature. A polyfill function is also included on that page.

**Comment by austin-rausch** [comment]
Oh, this is EMCA 6, not sure if its out of the scope for this module.

**Comment by austinkelleher** [comment]
Fixed in #3. Published `raptor-polyfill@1.1.0` with the change. Thanks!
